# Generated by Django 5.2.7 on 2025-11-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglist',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
